### ISSUE TITLE
colocar na página inicial as libs e frameworks [#1]

### ISSUE THREAD

**Issue by vianaV19** [Reynanwq/Happy-Cake#2]
Fala ai galera acho que seria legal vocês colocarem na página inicial quais são as libraries e frameworks utilizados para que os contribuidores já tenham a noção do que vão lidar no código. Ou seja, já saberão antes o que irão encontrar. Vlwww!.

**Comment by Reynanwq** [comment]
entendi, vamos colocar sim, muito obrigado pelo feedback!
